// This file is generated by Convex
// Run `npx convex dev` to regenerate

export const api: any = {
  incidents: {
    getIncidents: null,
    getTrucks: null,
    createIncident: null,
    updateTruckLocation: null,
    getNearbyTrucks: null,
  },
} as any;

