// This file is generated by Convex
// Run `npx convex dev` to regenerate

export const api: any = {} as any;

declare module "convex/_generated/api" {
  export const api: {
    incidents: {
      getIncidents: any;
      getTrucks: any;
      createIncident: any;
      updateTruckLocation: any;
      getNearbyTrucks: any;
    };
  };
}
