// This file is generated by Convex
// Run `npx convex dev` to regenerate
// This is a stub file for build purposes

export const query = () => {};
export const mutation = () => {};
export const action = () => {};
export const internalQuery = () => {};
export const internalMutation = () => {};
export const internalAction = () => {};

export type QueryCtx = any;
export type MutationCtx = any;
export type ActionCtx = any;
